apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-prometheus
spec:
  secretTargetRef:
  - parameter: bearerToken
    name: thanos-token-vkd6m
    key: token
  - parameter: ca
    name: thanos-token-vkd6m
    key: ca.crt
